#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Tie-Cycle
Version  : 1.225
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Tie-Cycle-1.225.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Tie-Cycle-1.225.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtie-cycle-perl/libtie-cycle-perl_1.225-1.debian.tar.xz
Summary  : 'Cycle through a list of values via a scalar.'
Group    : Development/Tools
License  : Artistic-2.0
Requires: perl-Tie-Cycle-license
Requires: perl-Tie-Cycle-man

%description
See the tests in the t/ directory for examples until I add some more.

%package license
Summary: license components for the perl-Tie-Cycle package.
Group: Default

%description license
license components for the perl-Tie-Cycle package.


%package man
Summary: man components for the perl-Tie-Cycle package.
Group: Default

%description man
man components for the perl-Tie-Cycle package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Tie-Cycle-1.225
mkdir -p %{_topdir}/BUILD/Tie-Cycle-1.225/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Tie-Cycle-1.225/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Tie-Cycle
cp LICENSE %{buildroot}/usr/share/doc/perl-Tie-Cycle/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Tie/Cycle.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Tie-Cycle/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Tie::Cycle.3
